services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "3808:8080"
    environment:
      - OLLAMA_BASE_URL=http://192.168.178.58:11434
    volumes:
      - open-webui:/app/backend/data
   
volumes:
  open-webui:
    external: true